name: Bug / Request / Improvement
description: File a bug report, feature request, or improvement proposal
title: "[Module-Name][bug|request|improvement] - Title"
labels: []
assignees: []
body:
  - type: input
    id: module
    attributes:
      label: Module
      description: Module or service impacted (match the title prefix).
      placeholder: e.g., payments-service
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Select the type of work.
      options:
        - bug
        - request
        - improvement
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Where this occurs and relevant version/build info.
      placeholder: e.g., production, staging, or local
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Clear, one to two sentence description of the issue or ask.
      placeholder: Provide a concise summary.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce (for bugs)
      description: Numbered steps to surface the bug.
      placeholder: |
        1. Go to...
        2. Click...
        3. See error...
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      description: What should happen.
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Result
      description: What happens instead.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Logs, screenshots, links to related tickets, or any other context that will help resolve the issue.
    validations:
      required: false
